Menambahkan sub-materi mengambil data ada materi database dasar
bellshade/PHP pull request #105
Opened 2021-10-29 18:19 UTC by wildanie12

Closes #99 

## Deskripsi (Description)

- [x] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [x] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [ ] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (I am using):

- `os` = `Windows 11`
- `web server` = `apache`
- `PHP version` = `PHP 7.4`
- `stack env` = `Yes, Laragon`
- `base url` = `bellshade.test/php-forked/ (sub directory)`

## Testing

- [x] Codesniffer PSR-12 `phpcs`
- [ ] Codesniffer autofix `phpcbf`
- [x] Unit testing PHPUnit

> Mention tidak dilakukan untuk percobaan otomasi workflow PR
> **Keterangan:** coba ikuti langkah-langkah yang ada di `README.md` untuk menjalankan demonya
> Di titik ini, seharusnya sudah terbentuk database dan beberapa sampel data yang sudah ada didalam tabel. Cek issue #98  untuk informasi selengkapnya atau baca `README.md` bagian membuat tabel

2021-10-30 04:57 UTC, wildanie12 commented
Bot Mention berhasil. Menunggu persetujuan kedua tim.

2021-10-30 05:11 UTC, Vins2106 approved these changes

2021-10-30 06:20 UTC, dhafitf approved these changes
Sepertinya sudah tidak ada typo. LGTM

2021-10-30 07:33 UTC, feri-irawan approved these changes
LGTM 👍🏻 Mantap om @wildanie12

2021-11-01 13:13 UTC, merged

2021-11-01 13:18 UTC, AdhyWiranto44 requested changes

2021-11-01 13:18 UTC, AdhyWiranto44 commented on basics/12_database_dasar_prosedural/4_mysqli_fetch.php
> +echo 'Hasil <strong>print_r($row):</strong> ', PHP_EOL;
`$row` pada string `print_r($row)` lebih baik dihapus saja agar tidak terjadi kebingunan. Karena jika dalam sisi tampilan, si pembaca nggak akan tau maksud $row di situ.

2021-11-01 13:18 UTC, AdhyWiranto44 commented on basics/12_database_dasar_prosedural/4_mysqli_fetch.php
> +echo 'Hasil <strong>print_r($row):</strong> ', PHP_EOL;
`$row` pada string `print_r($row)` lebih baik dihapus saja agar tidak terjadi kebingunan.

2021-11-01 13:18 UTC, AdhyWiranto44 commented on basics/12_database_dasar_prosedural/4_mysqli_fetch.php
> +echo 'Hasil <strong>print_r($row):</strong> ', PHP_EOL;
`$row` pada string `print_r($row)` lebih baik dihapus saja agar tidak terjadi kebingunan.

2021-11-01 14:50 UTC, wildanie12 commented on basics/12_database_dasar_prosedural/4_mysqli_fetch.php
> +echo 'Hasil <strong>print_r($row):</strong> ', PHP_EOL;
Waduh maaf banget om @AdhyWiranto44 PRnya sudah dimerged karena jumlah approvednya memberikan akses buat @mergify untuk melakukan merge.

Pada materi sebelumnya sudah dijelaskan kok om adhy tentang array dan bagaimana melakukan identifikasi array itu dengan menggunakan `print_r()`. 

Dan jika om Adhy melihat demonya, coba pertimbangkan untuk tetap menggunakan `print_r()` kembali. Karena saya rasa `print_r()` adalah cara terbaik untuk menjelaskan perbedaan dari beberapa fungsi `mysqli_fetch`. (misalnya perbedaan antara `mysqli_fetch_row()` dan `mysqli_fetch_assoc()`)
![image](https://user-images.githubusercontent.com/13761315/139690899-33503813-3e37-4f5b-8519-a4e4fab4672d.png)