Menambahkan materi basic Object Oriented Programing
bellshade/PHP pull request #106
Opened 2021-10-29 19:31 UTC by kondiak

Closes 

## Deskripsi (Description)

- [x] saya menambahkan materi basic baru berupa pengenalan OOP
- [x] saya memperbaiki materi basic yang sudah ada dalam materi Perulangan

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (I am using):

- `os` = `windows`
- `php version` = `8.0.8`
- `base url` = `localhost:8085`

## Testing

- [x] Codesniffer PSR-12 `phpcs`
- [x] Codesniffer autofix `phpcbf`
- [ ] Unit testing PHPUnit

## Maintainer
@bellshade/php-team
@bellshade/docs-team

1. Kali ini saya tambahkan sedikit mengenai infinite loop, walaupun dalam daftar materi tidak ada, saya merasa perlu untuk membuat ini karena hampir semua penulis kode pernah mengalami hal ini.
2. Saya mencoba menjelaskan materi mengenai OOP, pada saat ini baru sebatas pengenalan, untuk itu saya tidak mentag issue yang bersangkutan

2021-10-29 19:35 UTC, kondiak commented
Mohon untuk di periksa penyampaian mengenai OOP yang saya tulis, berhubung saya kesulitan menjelaskan apa itu OOP sesederhana mungkin dan mudah dimengerti. Untuk itu mohon masukan dari rekan-rekan team bellshade maupun para contributor.

sebelumnya atas masukan yang diberikan saya ucapkan terima kasih.

2021-10-30 02:37 UTC, wildanie12 approved these changes
Saya rasa udah cukup bagus untuk penjelasan fundamentalnya tentang basic pemrograman berorientasi objek.

Mungkin @bellshade/docs-team perlu mengkoreksi beberapa typo yang ada saja.

2021-10-30 04:21 UTC, slowy07 approved these changes

2021-10-30 05:10 UTC, Vins2106 approved these changes
LGTM

2021-10-30 06:09 UTC, dhafitf requested changes
Menurut KBBI, kata yang benar adalah `pemrograman` bukan `pemograman`.
Serta ada beberapa typo. Mohon diperbaiki.

2021-10-30 06:09 UTC, dhafitf commented on basics/14_oop_dasar/README.md
> +Sedangkan pemograman berorientasi terhadap objek semua hal dalam komputasi akan di ibaratkan sebagai sebuah objek yang terorganisir bertujuan membantu dalam menyelesaikan masalah komputasi. sehingga
```suggestion
Secara umum Pemrograman Prosedural berkerja secara terstruktur dengan cara memanggil prosedur-prosedur, prosedur ini berupa fungsi, rutinitas dan sub-rutinitas, melakukan pendekatan tahap demi tahap terhapat masalah komputasi, untuk memecahkan masalah tersebut menjadi variabel dan rutinitas melalui perintah-perintah terstruktur dan berurutan.

Dengan demikian pemrograman prosedural melakukan pendekatan dari atas dengan memecah sebuah program besar menjadi bagian bagian kecil berupa fungsi. Ini bekerja secara langsung secara logika megikuti alur. Data akan berpindah dari satu fungsi ke fungsi yang lain secara bebas.

Sedangkan pemrograman berorientasi terhadap objek semua hal dalam komputasi akan diibaratkan sebagai sebuah objek yang terorganisir bertujuan membantu dalam menyelesaikan masalah komputasi. Sehingga apapun dapat digambarkan ke dalam objek ini. Objek berisikan fungsi-fungsi dan atribute-atribute, dimana objek dapat digandakan dengan nilai dari atribut berbeda-beda tetapi dapat menjalankan fungsi yang sama. Karena bersifat modular objek dapat digunakan kembali. sehingga pengembangan dan perawatan sebuah aplikasi menjadi lebih mudah. Data dalam properti dan metode objek dapat diproteksi dengan encapsulasi dan pemberikan batas hak akses modifikasi dimana dalam OOP dibagi 3 kelompok yaitu, private, protected, public dengan demikian data dirasa "lebih aman" dari pada pemrograman prosedural.
```

2021-10-30 06:09 UTC, dhafitf commented on basics/14_oop_dasar/README.md
> +Dibawah ini sebuah contoh sederhana baris kode menggunakan pendekatan prosedural dan pendekatan secara objek untuk membuat sebuah array, menambahkan nilai kedalam array kemudian memanggil nilai terse
```suggestion
Di bawah ini sebuah contoh sederhana baris kode menggunakan pendekatan prosedural dan pendekatan secara objek untuk membuat sebuah array, menambahkan nilai ke dalam array kemudian memanggil nilai tersebut.
```

2021-10-30 06:09 UTC, dhafitf commented on basics/5_perulangan/README.md
> +Maka baris kode di akan akan selalu melakukan print nilai `0` tanpa henti, karena setiap perlungan dilakukan nilai dari variable $i akan kembali menjadi `0` sehingga menyebabkan ekspresi 1 < 5 adalah
```suggestion
Maka baris kode di atas akan selalu melakukan print nilai `0` tanpa henti, karena setiap perulangan dilakukan nilai dari variable $i akan kembali menjadi `0` sehingga menyebabkan ekspresi 1 < 5 adalah benar-`true`.
```

2021-10-30 06:09 UTC, dhafitf commented on basics/5_perulangan/README.md
> +    Tunggu saja beberapa detik, biasa settingan php mempunyai masa time out selama 30 detik, bila dalam 30 detik tidak berhenti, kemungkian konfigurasi ini telah diganti, kita dapat menggunakan tombo
```suggestion
    Tunggu saja beberapa detik, biasa settingan php mempunyai masa time out selama 30 detik, bila dalam 30 detik tidak berhenti, kemungkinan konfigurasi ini telah diganti, kita dapat menggunakan tombol stop pada browser kita untuk menghentikan perulangan ini.
```

2021-10-30 06:09 UTC, dhafitf commented on basics/5_perulangan/README.md
> +Dalam pengebangan aplikasi ada kalanya kita akan melakukan loop yang sangat banyak seperti dalam pencarian, jika kita ragu terhadap perulangan yang kita lakukan kita dapat menyelipkan fungsi `break`
```suggestion
Dalam pengembangan aplikasi ada kalanya kita akan melakukan loop yang sangat banyak seperti dalam pencarian, jika kita ragu terhadap perulangan yang kita lakukan kita dapat menyelipkan fungsi `break` dalam perulangan kita yang kemudian dapat kita hilangkan jika kita rasa perulangan tersebut telah berjalan dengan benar, sebagai contoh baris kode dibawah ini :
```

2021-10-30 06:09 UTC, dhafitf commented on basics/5_perulangan/README.md
> +Dimana kita seharusnya menggunakan operator pembanding(`==`,`===`) tapi tanpa sengaja kita menggukan operator penugasan(`=`). Kemudian kita dapat memperbaiki perulangan yang kita buat.
```suggestion
Dimana kita seharusnya menggunakan operator pembanding(`==`,`===`) tapi tanpa sengaja kita menggunakan operator penugasan(`=`). Kemudian kita dapat memperbaiki perulangan yang kita buat.
```

2021-10-30 06:09 UTC, dhafitf commented on basics/5_perulangan/README.md
> +Setelah kita jalankan script PHP tersebut dan kita merasa bahwa perulangan yang terjadi sudah benar, kita dapat menghapus baris kode dari pencegahan perulangan tersebut. atau dengan cara lain jika me
```suggestion
Setelah kita jalankan script PHP tersebut dan kita merasa bahwa perulangan yang terjadi sudah benar, kita dapat menghapus baris kode dari pencegahan perulangan tersebut. Atau dengan cara lain jika menggunakan operator persamaan dalam ekspresi, kita dapat membalik posisi variabel dan nilai, jika kita salah memasukkan operator hal ini hanya akan menimbulkan pesan kesalahan. Contoh :
```

2021-10-30 06:27 UTC, wildanie12 commented
Saya ambil alih om @kondiak. Saya pingin sedikit kontribusi juga ke pengenalan OOP ini juga lewat PR ini.
Sekalin saya fix typonya.
btw.. kebanyakan udah mantep om. 👍

2021-10-30 07:24 UTC, kondiak commented
> 
> 
> Saya ambil alih om @kondiak. Saya pingin sedikit kontribusi juga ke pengenalan OOP ini juga lewat PR ini. Sekalin saya fix typonya. btw.. kebanyakan udah mantep om. 👍

maksud om @wildanie12 , perbaikannya om yang ngerjain gitu ya, sekalian sama lanjutan nya gak?, kalau iya saya titip nih class sama object, nanggu udah rampung

2021-10-30 07:27 UTC, kondiak commented
## Kelas dan Objek

Dalam paradigma pemograman OOP kita akan sering mendengar istilah Kelas (`class`) dan objek (`object`), `class` dan `object` saling berhubungan, tidak akan ada sebuah `object` tanpa `class`, dan tidak akan berguna sebuah `class` tanpa `object`, dan `object` merupakan elemen dasar dari pemograman berorientasi terhadap objek.

### Kelas (class)

`Class` adalah sebuah template atau pola yang berfungsi untuk membuat sebuah `object`, `class` mendefinisikan properti, atribut dan bahkan tugas-tugas yang bisa dilakukan atau tanggung jawab sebuah `object`.
Contoh kita membuat `class` yang mendefinisikan sebuah Smartphone. Smartphone itu didefiniskan sebagai sebuah telepon portable yang memiliki kamera, akses jaringan internet, Wi-Fi, yang memiliki kemampuan untuk melakukan panggilan, dan menerima panggilan, mengambil gambar, mengakses internet, dan lainnya, semua itu tertuang dalam `class`, dengan `class` tersebut kita bisa menulis atau menyatakan sebuah `object` baru sebagai smartphone contoh samaun S11, dimana `object` baru tersebut memiliki properti dan fungsi sesuai dengan `class` tadi, mungkin kita mendapati kekurangan dari smartphone tersebut, seperti sim card yang belum ada, charger, kabel data, headset, contact yang akan dihubungi dan beberapa aplikasi yang belum terpasang, karena kita meletakan hal tersebut diluar `class` yang kemudian akan menjadi parameter input.

Kesimpulan `class` mendefinisikan variable yang disebut `property` dan fungsi yang disebut `method` atau metode yang akan menentukan sebuah objek. Sampai disini mudah-mudahan kita sudah dapat memahami sedikit mengenai `class` dalam pemograman PHP.

`class` dalam PHP kita tuliskan dalam contoh baris kode berikut:

```php
<?php
class Smartphone
{
    //Properti
    public $merk;
    public $type;
    public $os;

    //Metode (Method)
    public function setMerk($merk)
    {
        $this->merk = $merk;
    }

    public function setType($type)
    {
        $this->type = $type
    }

    public function LakukanTelepon($nomor)
    {
        echo "Lakukan telepon ke nomor " . $nomor;
    }
}
?>
```

>info:  
>variabel $this dalam class menyatakan class itu sendiri, tanda panah (->) menunjukan properti atau method yang harus dilakukan sebuah class.


### Objek (object)

Sudah beberapa kali disinggung mengenai `object` adalah instansiasi dari sebuah `class`. `object` adalah bentuk nyata dari sebuah `class`, dalam kehidupan sehari-hari `object` ini bukan hanya sebuah benda atau mahluk yang dapat dilihat atau di rasakan tetapi juga hal-hal yang memiliki nilai properti dan fungsi, sebagai contoh rekening bank, bahasa, dan lainnya. Hampir semua dapat dijadikan sebuah `object` dalam pemograman OOP.

`object` dapat bekerja untuk melakukan tugas tertentu tanpa yang memberi perintah harus tau bagaimana sebuah `object` melakukannya. Seorang pengembang akan menulis tugas yang dapat dilaksanakan oleh `object` dalam sebuah `class`, dia tau apa yang dikerjakan sebuah `object` untu menyelesaikan tugasnya, semua orang dapat menggunakan `class` tersebut, tetapi tidak begitu penting mengetahui bagaimana sebuah dia menyelesaikan tugasnya saat kita menggunakannya.

Kita analogikan kembali seperti sebelumnya, Badan Standarisasi telah mendefiniskan apa itu sebuah "Smartphone", kemudian perusahan-perusahan teknologi membuat sebuah produk berupa "telepon selular"-ponsel dengan merk dan type berbeda dengan fungsi sesuai dengan yang ditetapkan Badan Standarisasi tadi, Kita tidak tau cara ponsel tersebut melakukan panggilan, tetapi kita bisa menggunakannya untuk menelepon.

Oke kita kembali ke PHP, untuk menggunakan `object` kita harus meng-instansiasikan sebuah `class` dalam bentuk variabel dimana variabel inilah yang akan disebut sebagai sebuah `object`, sebagai contoh pada baris kode berikut :

```php
<?php
    class SmartPhone
    {
        ......
    }

    $samaun_s11 = new SmartPhone();         //Object
    $iPunX = new SmartPhone();              //Object
    $Siomay = new SmartPhone();             //Object
?>
```

Nah dapat kita lihat pada baris kode diatas `Class` dapat dijadikan beberapa `object`.

2021-10-30 07:43 UTC, wildanie12 commented
Hmmm.. oke deh, thank @kondiak. Kita jadikan 1 PR aja berarti yah. 👍

2021-11-01 01:52 UTC, slowy07 commented
@Mergifyio refresh

2021-11-01 01:52 UTC, slowy07 commented
cek detail dari bot mergifynya kak @wildanie12 💯

2021-11-01 15:39 UTC, Vins2106 approved these changes

2021-11-01 15:57 UTC, slowy07 approved these changes

2021-11-05 01:14 UTC, feri-irawan commented on basics/14_oop_dasar/README.md
> +Dalam materi sebelumnya kita sudah mencoba membuat contoh-contoh baris kode yang rata-rata baris kode tersebut merupakan pola kerja pemograman prosedural atau pemograman terstruktur. dalam pemograman
```suggestion
## 1. Pengenalan Pemograman Berorientasi Objek

Dalam materi sebelumnya kita sudah mencoba membuat contoh-contoh baris kode yang rata-rata baris kode tersebut merupakan pola kerja pemograman prosedural atau pemograman terstruktur. dalam pemograman ada yang disebut sebagai Paradigma Pemograman yaitu sudut pandang seorang programer dalam menyelesaikan suatu kasus atau masalah dengan cara pemograman. Hal ini penting bagi seorang programer untuk mengidentifikasi permasalahan dan menyusun sebuah solusi dalam bentuk pemograman.
```

2021-11-23 04:50 UTC, wildanie12 commented
Halo om @kondiak. Disini saya merombak beberapa hasil kerjaan saya dengan om Kondiak.. Karena saya rasa ada yang lebih baik lagi tentang fundamental metode pemrograman OOP. Jadi PR yang terakhir adalah hasil kerja antara saya dan om Kondiak. 

Lalu saya rasa untuk kelas dan objek (Issue #108) lebih baik diikutkan untuk PR selanjutnya, om @kondiak jika mau bisa juga submit PR lagi untuk issue ini om.

2021-11-23 04:59 UTC, kondiak commented
Bagus tuh om @wildanie12, cakeppppp

2021-11-23 10:43 UTC, kondiak commented
> Halo om @kondiak. Disini saya merombak beberapa hasil kerjaan saya dengan om Kondiak.. Karena saya rasa ada yang lebih baik lagi tentang fundamental metode pemrograman OOP. Jadi PR yang terakhir adalah hasil kerja antara saya dan om Kondiak. 
> 
> Lalu saya rasa untuk kelas dan objek (Issue #108) lebih baik diikutkan untuk PR selanjutnya, om @kondiak jika mau bisa juga submit PR lagi untuk issue ini om.

Untuk #108 mungkin harus di perbaharui juga om, soalnya tema udah beda, kalau di awal bahas nya rumah makan, harus konsisten ke belakang rumah makan

2021-11-23 12:24 UTC, wildanie12 commented
@

> > Halo om @kondiak. Disini saya merombak beberapa hasil kerjaan saya dengan om Kondiak.. Karena saya rasa ada yang lebih baik lagi tentang fundamental metode pemrograman OOP. Jadi PR yang terakhir adalah hasil kerja antara saya dan om Kondiak.
> > Lalu saya rasa untuk kelas dan objek (Issue #108) lebih baik diikutkan untuk PR selanjutnya, om @kondiak jika mau bisa juga submit PR lagi untuk issue ini om.
> 
> Untuk #108 mungkin harus di perbaharui juga om, soalnya tema udah beda, kalau di awal bahas nya rumah makan, harus konsisten ke belakang rumah makan, soalnya kalau berubah di tiap sub materi, pemahaman akan paradigma OOP takutnya gak sampai

Tentu om.. Issue akan di evaluasi lagi dan diperbarui. Sebelumnya mohoh maaf yah klo sebelumnya aktifitas di bellshade PHP  agak menurun, tapi sekarang mulai ditingkatkan lagi. Lalu maaf juga yah klo topik analoginya saya rubah. Semuanya harapannya bisa mempermudah bagi yang menggunakan repo ini buat belajar.

2021-11-23 13:15 UTC, kondiak commented
> @
> 
> > > Halo om @kondiak. Disini saya merombak beberapa hasil kerjaan saya dengan om Kondiak.. Karena saya rasa ada yang lebih baik lagi tentang fundamental metode pemrograman OOP. Jadi PR yang terakhir adalah hasil kerja antara saya dan om Kondiak.
> > > Lalu saya rasa untuk kelas dan objek (Issue #108) lebih baik diikutkan untuk PR selanjutnya, om @kondiak jika mau bisa juga submit PR lagi untuk issue ini om.
> > 
> > Untuk #108 mungkin harus di perbaharui juga om, soalnya tema udah beda, kalau di awal bahas nya rumah makan, harus konsisten ke belakang rumah makan, soalnya kalau berubah di tiap sub materi, pemahaman akan paradigma OOP takutnya gak sampai
> 
> Tentu om.. Issue akan di evaluasi lagi dan diperbarui. Sebelumnya mohoh maaf yah klo sebelumnya aktifitas di bellshade PHP  agak menurun, tapi sekarang mulai ditingkatkan lagi. Lalu maaf juga yah klo topik analoginya saya rubah. Semuanya harapannya bisa mempermudah bagi yang menggunakan repo ini buat belajar.

Perubahan untuk jadi lebih baik pasti.!!!.

2021-11-23 13:53 UTC, azqilana requested changes
Saya sangat suka dengan analogi  yang ada tp ada sedikit perubahan yang saya ajukan pada analogi yang sudah di ketik tolong di pertimbangkan untuk melakukan prubahan sesuai request dari saya om @wildanie12

2021-11-23 13:53 UTC, azqilana commented on basics/14_oop_dasar/README.md
> +Jika kita analogikan pada kehidupan sehari-hari, bayangkan ada sebuah restoran makanan. Agar usaha restoran tersebut dapat berjalan, semua aktifitas dalam restoran tersebut terbagi menjadi beberapa b
```suggestion
Jika kita analogikan pada kehidupan sehari-hari, bayangkan ada sebuah restoran makanan. Agar pelayanan pada restoran tersebut dapat berjalan dengan efisien, semua aktifitas dalam restoran tersebut dirbagi menjadi beberapa bagian. Ada yang jadi pelayan, ada yang di kasir, ada yang memasak di dapur,dsb. Jika kamu perhatikan, pecahan bagian-bagian ini mempunyai tugasnya sendiri-sendiri dan memiliki prosedur masing-masing. Akan tetapi satu bagian harus tetap berhubungan dengan bagian-bagian lainnya agar restoran bisa berjalan dengan lancar dan efisien.
```

2021-11-23 13:53 UTC, azqilana commented on basics/14_oop_dasar/README.md
> +Jika kita menggunakan kembali analogi sebelumnya, pemrograman dengan cara prosedural dapat diibaratkan dengan melakukan pelayanan makanan secara berurutan mulai menerima pesanan, memasak di dapur sam
```suggestion
Jika kita menggunakan kembali kepada analogi sebelumnya, pemrograman dengan cara prosedural dapat diibaratkan dengan melakukan pelayanan makanan secara berurutan mulai menerima pesanan, memasak di dapur sampai memberikan makanan ke pelanggan di lakukan sendiri oleh satu orang, sehingga pelayanan terhadap pelanggan berjalan dengan tidak efisien yang menunjukan  _standar operational procedure_ (SOP) yang tidak baik.
```

2021-11-23 13:53 UTC, azqilana commented on basics/14_oop_dasar/README.md
> +Sama halnya dengan pemrograman sebenarnya. Misalnya pada implementasi form tambah data barang, hal-hal yang diimplementasikan pastinya dimulai dengan: menampilkan form, mempopulasikan data barang, me
```suggestion
Sama halnya dengan pemrograman sebenarnya. Misalnya pada implementasi form tambah data barang, hal-hal yang diimplementasikan pastinya dimulai dengan:
- Menampilkan form 
- Mempopulasikan data barang,
- Melakukan validasi
- Dan menambahkan rekam data ke database
 Jika menggunakan metode prosedural, biasanya semua itu dilakukan secara berurutan dalam satu file sehingga jika kita ingin membuat edit data barang yang  memiliki banyak kesamaan dengan tambah data barang maka harus membuat ulang dan melakukan hal yang sama sehingga akan terjadi duplikasi pada code.
```

2021-11-23 14:14 UTC, wildanie12 commented on basics/14_oop_dasar/README.md
> +Jika kita analogikan pada kehidupan sehari-hari, bayangkan ada sebuah restoran makanan. Agar usaha restoran tersebut dapat berjalan, semua aktifitas dalam restoran tersebut terbagi menjadi beberapa b
LGTM .. bakal diterapkan pada perubahan

2021-11-23 14:35 UTC, feri-irawan approved these changes
Sip om, LGTM 👍🏻

2021-11-24 05:36 UTC, wildanie12 commented on basics/14_oop_dasar/README.md
> +Jika kita menggunakan kembali analogi sebelumnya, pemrograman dengan cara prosedural dapat diibaratkan dengan melakukan pelayanan makanan secara berurutan mulai menerima pesanan, memasak di dapur sam
Ah ini saya sanggah deh. Paragraf itu ide utamanya adalah menggambarkan ketidakteraturan _usecase_ dan struktur kode jika menggunakan metode penulisan prosedural. Jadi saya peringkas lagi saja tanpa menghilangkan ide utamanya.
Perbaruan bakal ada di commit berikutnya.

2021-11-24 05:46 UTC, wildanie12 commented on basics/14_oop_dasar/README.md
> +Sama halnya dengan pemrograman sebenarnya. Misalnya pada implementasi form tambah data barang, hal-hal yang diimplementasikan pastinya dimulai dengan: menampilkan form, mempopulasikan data barang, me
Yep.. saya rasa bagus begitu

2021-11-24 05:56 UTC, wildanie12 commented
Saya sudah memperbarui dokumentasi pada file markdown `README.md`. Semua koreksi request diterapkan kecuali yang kedua tentang ide paragraf analogi metode prosedural. Namun paragraf itu juga diperbarui dan diperingkas agar bisa lebih mudah dibaca. Terakhir saya koreksi juga kata `diasingkan`, saya rasa `disendirikan` lebih sering umum dipake.

Silahkan direview lagi @bellshade/php-team @azqilana

2021-11-26 07:36 UTC, azqilana commented on basics/14_oop_dasar/README.md
> +Sama halnya dengan pemrograman sebenarnya. Misalnya pada implementasi form tambah data barang, hal-hal yang diimplementasikan pastinya dimulai dengan: menampilkan form, mempopulasikan data barang, me
oke om

2021-11-26 07:38 UTC, azqilana commented
> Saya sudah memperbarui dokumentasi pada file markdown `README.md`. Semua koreksi request diterapkan kecuali yang kedua tentang ide paragraf analogi metode prosedural. Namun paragraf itu juga diperbarui dan diperingkas agar bisa lebih mudah dibaca. Terakhir saya koreksi juga kata `diasingkan`, saya rasa `disendirikan` lebih sering umum dipake.
> 
> Silahkan direview lagi @bellshade/php-team @azqilana

oke om saysa periksa

2021-11-26 07:45 UTC, azqilana approved these changes
oke om lgtm

2021-11-27 12:47 UTC, merged