docs: Dokumentasi Materi Basic, Sub Materi Fungsi Dasar
bellshade/PHP pull request #112
Opened 2021-10-30 14:06 UTC by kondiak

Closes #23 

## Deskripsi (Description)

- [ ] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [x] saya menambahkan dokumentasi/artikel baru
- [x] saya memperbaiki dokumentasi/artikel yang sudah ada
- [ ] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (I am using):

- `os` = `windows`

## Testing

- [ ] Codesniffer PSR-12 `phpcs`
- [ ] Codesniffer autofix `phpcbf`
- [ ] Unit testing PHPUnit

## Maintainer
@bellshade/php-team
@bellshade/docs-team

Materi ini belum melengkapi  semua sub materi pada Basic : Fungsi Dasar

2021-11-06 12:56 UTC, feri-irawan requested changes

2021-11-06 12:56 UTC, feri-irawan commented on basics/8_fungsi_dasar/README.md
> +    withParameter("Contoh");    //saya fungsi, menerima parameter Contoh
Hai, kak @kondiak sedikit koreksi. Sepertinya akan lebih baik jika kak @kondiak  menggunakan standar penulisan kode yang sama dengan yang disebutkan pada `CONTIBUTING.md` untuk menulis kode pada penjelasan materi seperti yang ada di `README.md` ini ataupun pada file demo (file `.php`) agar lebih konsisten lagi

2021-11-07 02:52 UTC, kondiak commented on basics/8_fungsi_dasar/README.md
> +    withParameter("Contoh");    //saya fungsi, menerima parameter Contoh
Siap om @feri-irawan , segera saya perbaiki

2021-11-08 04:57 UTC, wildanie12 approved these changes
Saya rasa sudah cukup baik. Terima kasih om @kondiak 🙏
Karena masih ada kekurangan sedikit, kita akan tetap buka Issuenya yah 👍

2021-11-21 12:15 UTC, merged