add: menambahkan algoritma FizzBuzz
bellshade/PHP pull request #126
Opened 2021-11-04 12:59 UTC by KrOxYs

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [ ] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [x] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan ():

- `os` = `linux / windows / macOS`

## Testing

- [ ] Codesniffer PSR-12 `phpcs`
- [ ] Codesniffer autofix `phpcbf`
- [x] Unit testing PHPUnit

## Maintainer

2021-11-04 13:16 UTC, feri-irawan requested changes
Maaf kak, pastikan sebelum commit, kakak sudah menjalankan perintah `composer phpcs` lalu `composer phpcbf` agar penulisan kode PHP yang kakak tulis otomatis diperbaiki dan sesuai dengan standar penulisan yang telah disebutkan di [CONTRIBUTING.md](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) 

Silakan jalankan perintah-perintah di atas, commit

2021-11-04 23:30 UTC, AdhyWiranto44 commented
Kodenya harus dibarengi dengan file Readme.md ya sebagai penjelasan materi mengenai algoritma FizzBuzz ini, Coba dilihat contoh yang sudah ada, sesuaikan ya biar rapi :D

2021-11-05 01:09 UTC, feri-irawan requested changes

2021-11-05 01:09 UTC, feri-irawan commented on algorithms/FizzBuzz.php
> +    };
Kenapa menambahkan titik koma pada penutup `else` dan `for`?

2021-11-05 01:33 UTC, closed without merging