add: Menambah Materi Session dan Cookie
bellshade/PHP pull request #127
Opened 2021-11-07 09:22 UTC by feri-irawan

Close #82 

## Deskripsi (Description)

- [x] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [x] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [ ] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (I am using):

- `os` = `windows`

## Testing

- [x] Codesniffer PSR-12 `phpcs`
- [x] Codesniffer autofix `phpcbf`
- [ ] Unit testing PHPUnit

## Maintainer

2021-11-07 09:45 UTC, azqilana requested changes
menurut saya sudah oke jd cukup edit sesuai yang saya tandai saja fer

2021-11-07 09:45 UTC, azqilana commented on basics/11_cookie_dan_session/2_get_session.php
> +
kenapa membuat sessionnya di ulang lagi seharusnya cukup kasih tau lewat komentar jika sebelum nya di file sebelumnya sudah membuat season

2021-11-07 09:45 UTC, azqilana commented on basics/11_cookie_dan_session/3_update_session.php
> +
di sini juga sama kasih tau lewat komentar saja

2021-11-07 09:51 UTC, azqilana commented on basics/11_cookie_dan_session/3_update_session.php
> +print_r($_SESSION);
di sini juga sama kasih tau lewat komentar saja jadi  hapus aja baris 9 - 17 nya yang di file 3_update_session.php

2021-11-07 10:21 UTC, feri-irawan commented on basics/11_cookie_dan_session/2_get_session.php
> +
Sengaja itu om, biar kelihatan kalau sessionnya sudah dibuat, kita kan gk tau user itu dah buka file sebelumnya atau tidak, kan bisa saja diskip, jadi saya buat lagi.

2021-11-07 13:29 UTC, azqilana commented on basics/11_cookie_dan_session/2_get_session.php
> +
om @feri-irawan sepertinya bisa minta user untuk lihat file sebelumnya pake komentar  biar user belajar terurut gitu

2021-11-07 14:51 UTC, feri-irawan commented on basics/11_cookie_dan_session/2_get_session.php
> +
@azqilana itu bisa" membuat newbie kebingungan bolak" balik file om. Di sini kita memikirkan beginner friendly, membuat visualisai yang tidak membingungkan. Walapun mungkin di materi ini ada beberapa yg membingungkan, saya sudah usahakan agar materinya mudah di serap

2021-11-07 15:05 UTC, azqilana commented on basics/11_cookie_dan_session/2_get_session.php
> +
kan di readme nya itu sudah ada

2021-11-08 03:11 UTC, feri-irawan commented on basics/11_cookie_dan_session/2_get_session.php
> +
@azqilana coba om di clone dulu, dan rasakan visualisasinya 👍🏻

2021-11-08 04:09 UTC, dhafitf approved these changes
Sepertinya sudah tidak ada typo pada file materi. 👍

2021-11-08 04:14 UTC, wildanie12 requested changes
Mantep om fer, sangat lengkap sekali. _Nicely done_
Tapi sedikit _minor problem_ gimana kalau pada `6_update_cookie.php`, yang diupdate cookienya bukan `buah_manis` tapi `tim` aja. Soalnya, jika pake `buah_manis`, terlalu banyak kondisi untuk cookie tersebut bisa aktif. Jadi pas dicoba di web server lain (Laragon) yang urlnya `xxx.test` dan `xxx.test/php`, cookienya sendiri tidak aktif, yang akhirnya `6_update_cookie.php` ngga jalan sama sekali.

2021-11-08 04:19 UTC, wildanie12 commented on basics/11_cookie_dan_session/3_update_session.php
> +print_r($_SESSION);
Klo menurutku dah oke kayanya. Takutnya jika disuruh hapus beberapa baris kode, jadi ngga praktis buat yang lagi belajar. Selama penjelasan dari materi yang tertulis di `README.md` udah cukup jelas, Demo seperti ini kayanya udah cukup bagus.

2021-11-08 04:37 UTC, azqilana commented on basics/11_cookie_dan_session/3_update_session.php
> +print_r($_SESSION);
ya sudah ana mau lihat pendapat yang lain om kalok yg lain kalok enggak ada yang omentarin soal code saya approve nanti aja

2021-11-08 04:37 UTC, azqilana commented
> Mantep om fer, sangat lengkap sekali. _Nicely done_ Tapi sedikit _minor problem_ gimana kalau pada `6_update_cookie.php`, yang diupdate cookienya bukan `buah_manis` tapi `tim` aja. Soalnya, jika pake `buah_manis`, terlalu banyak kondisi untuk cookie tersebut bisa aktif. Jadi pas dicoba di web server lain (Laragon) yang urlnya `xxx.test` dan `xxx.test/php`, cookienya sendiri tidak aktif, yang akhirnya `6_update_cookie.php` ngga jalan sama sekali.

baru mau saya coba udah tau erornya ngga jadi saya coba lah

2021-11-08 04:43 UTC, wildanie12 commented on basics/11_cookie_dan_session/2_get_session.php
> +
Yep.. Visualisasinya dah oke, memang terbatas banget soal demonya tapi selama sudah dijelaskan dengan bagus di `README.md`, demo seperti ini udah cukup bagus.
di materi database juga kurang lebih seperti ini teknis demo materinya jadi saya rasa udah cukup bagus.

2021-11-08 04:44 UTC, wildanie12 commented on basics/11_cookie_dan_session/2_get_session.php
> +
Resolved yaah .. 👍🏻

2021-11-08 09:34 UTC, feri-irawan commented
> Mantep om fer, sangat lengkap sekali. _Nicely done_ Tapi sedikit _minor problem_ gimana kalau pada `6_update_cookie.php`, yang diupdate cookienya bukan `buah_manis` tapi `tim` aja. Soalnya, jika pake `buah_manis`, terlalu banyak kondisi untuk cookie tersebut bisa aktif. Jadi pas dicoba di web server lain (Laragon) yang urlnya `xxx.test` dan `xxx.test/php`, cookienya sendiri tidak aktif, yang akhirnya `6_update_cookie.php` ngga jalan sama sekali.

Siap om @wildanie12 itu akan saya lakukan

2021-11-09 11:45 UTC, feri-irawan commented
Sip, om @wildanie12 @azqilana , penjelasan untuk bagian **Mengubah Cookie** sudah saya perbaiki dan demonya juga sudah saya ganti. Silakan direview!

2021-11-09 12:06 UTC, azqilana approved these changes
bagus om

2021-11-09 16:16 UTC, dhafitf approved these changes
Mantap, dari segi dokumentasi masih aman

2021-11-10 16:32 UTC, wildanie12 approved these changes
LGTM 👍

2021-11-10 16:32 UTC, merged