add: menambah materi stripslashes
bellshade/PHP pull request #131
Opened 2021-11-24 04:08 UTC by KrOxYs

Closes 

## Deskripsi (Description)

- [x] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [ ] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [ ] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (windows):

- `os` = `linux / windows / macOS`

## Testing

- [ ] Codesniffer PSR-12 `phpcs`
- [ ] Codesniffer autofix `phpcbf`
- [x] Unit testing PHPUnit

## Maintainer

2021-11-24 05:32 UTC, azqilana reviewed
@KrOxYs  terlalu to do point anda

2021-11-27 11:01 UTC, ikr4mm requested changes
Dari dokumentasi menurut saya sudah bagus namun ada beberapa yang mesti diralat. Semisalnya ada yang ditanyakan atau perlu disanggah bisa langsung dikomentar saja.

*Dan juga, saya melihat file yang aneh, kira-kira bisa dijelaskan itu apa?*

2021-11-28 07:42 UTC, azqilana commented on env.env
> +BASE_URL = 'http://localhost/PHP'
itu file env udah baca contributing.md disana ada di bahas

2021-11-29 06:27 UTC, azqilana commented on basics/6_manipulasi_string/README.md
> +`stripslashes()` berfungsi untuk menghilangkan backslash dalam sebuah string.
sudah ya om

2021-11-29 07:29 UTC, feri-irawan requested changes

2021-11-29 07:29 UTC, feri-irawan commented on basics/6_manipulasi_string/6_strip_slashes.php
> +$text = "Ayo belajar \di bellshade";
Mungkin untuk contoh string-nya bisa diganti dengan _string yg memiliki tanda petik dua (") dan diapit dengan petik dua juga_, karna `stripslashes` sering kali digunakan pada string seperti itu, seperti menngambil data dari JSON dan lainnya.

Misal : `"Wildani: \"Hai, apa kabar semuanya?\""`

2021-11-29 07:32 UTC, azqilana commented on basics/6_manipulasi_string/6_strip_slashes.php
> +$text = "Ayo belajar \di bellshade";
oke

2021-11-29 07:36 UTC, azqilana commented on basics/6_manipulasi_string/6_strip_slashes.php
> +$text = "Ayo belajar \di bellshade";
sudah

2021-11-29 07:38 UTC, feri-irawan commented on basics/6_manipulasi_string/6_strip_slashes.php
> +$text = "Ayo belajar \di bellshade";
oh iya om @azqilana sertakan juga output dari codingannya di dalam kode dalam bentuk komentar, agar ketika org buka kodingannya bisa lihat hasil dari kodingannya tanpa menjalankannya, misal dia belajar via github, bukan di lokal.

2021-11-29 07:39 UTC, feri-irawan commented on basics/6_manipulasi_string/6_strip_slashes.php
> +$text = "Ayo belajar \di bellshade";
oh iya om @azqilana sertakan juga output dari codingannya di dalam kode dalam bentuk komentar, agar ketika org buka kodingannya bisa lihat hasil dari kodingannya tanpa menjalankannya, misal dia belajar via github, bukan di lokal.

2021-11-29 07:49 UTC, azqilana commented on basics/6_manipulasi_string/6_strip_slashes.php
> +$text = "Ayo belajar \di bellshade";
oke td lupa

2021-12-01 11:28 UTC, feri-irawan approved these changes
LGTM 👍🏻

2021-12-01 16:06 UTC, slowy07 commented
@Mergifyio refresh

2021-12-01 16:52 UTC, azqilana approved these changes
LGTM

2021-12-02 15:23 UTC, ikr4mm approved these changes
Looks good to me!

2021-12-04 13:07 UTC, merged