add: menambah materi oop dasar class dan object
bellshade/PHP pull request #133
Opened 2021-12-07 05:56 UTC by KrOxYs

Closes 

## Deskripsi (Description)

- [x] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [ ] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [ ] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (windows):

- `os` = `linux / windows / macOS`

## Testing

- [ ] Codesniffer PSR-12 `phpcs`
- [ ] Codesniffer autofix `phpcbf`
- [x] Unit testing PHPUnit

## Maintainer

2021-12-09 05:49 UTC, wildanie12 requested changes
Lumayan bagus. Tinggal format headingnya yang ngga konsisten sama yang sudah ada diatas.
Lalu jangan terlalu banyak pake heading dengan huruf besar. 

Dan tambahkan juga anchor link daftar isi yang mengarah ke heading `2. Class dan Object`

![image](https://user-images.githubusercontent.com/13761315/145341626-75be18c8-784f-496d-b3c4-a6fa8773a11b.png)

2021-12-09 07:45 UTC, wildanie12 approved these changes

2021-12-09 08:02 UTC, azqilana approved these changes
approve lah  thank you for you contribution

2021-12-11 09:31 UTC, kondiak approved these changes
Oke nih

2021-12-12 03:19 UTC, ikr4mm requested changes
Penjelasan sudah bagus, akan tetapi ada _sedikit_ catatan.

Semisal ada alasan yang kuat untuk mempertahankan tersebut, bisa langsung diberi komentar.

2021-12-12 03:19 UTC, ikr4mm commented on basics/14_oop_dasar/README.md
> +Dari sini bisa dibilang bahwa `buku` adalah sebuah class dan `HandPhone` Adalah sebuah objectnya,
Disarankan tidak usah dijadikan subbab, hapus line 73

2021-12-12 12:00 UTC, KrOxYs commented on basics/14_oop_dasar/README.md
> +Dari sini bisa dibilang bahwa `buku` adalah sebuah class dan `HandPhone` Adalah sebuah objectnya,
Sudah Di Perbaiki Silahkan Di Cek

2021-12-14 10:21 UTC, ikr4mm approved these changes
LGTM 🚀🚀

2021-12-14 17:57 UTC, merged