Berylium
bellshade/PHP pull request #135
Opened 2021-12-10 06:44 UTC by kondiak

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [ ] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [x] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (I am using):

- `os` = `windows`

## Testing

- [x] Codesniffer PSR-12 `phpcs`
- [x] Codesniffer autofix `phpcbf`
- [x] Unit testing PHPUnit

## Maintainer

2021-12-12 03:30 UTC, ikr4mm requested changes
Mungkin karena saya ceknya di hape jadi ada beberapa yang terlewat. Sebisanya konsisten untuk penggunaan prefix "di-".

Semisal ada alasan yang kuat untuk mempertahankan tersebut, bisa langsung diberi komentar.

2021-12-12 03:30 UTC, ikr4mm commented on algorithms/Searching/Ternary/README.md
> +Ternary Search dari namanya algoritma ini termasuk kedalam algoritma pencarian, algortima ini melakukan pencarian dengan menggunakan 2 cursor atau 2 tempat sekaligus, dimana kedua tempat ini akan mem
"... ini termasuk **ke dalam** algoritma pencarian ..."

2021-12-12 03:30 UTC, ikr4mm commented on algorithms/Searching/Ternary/README.md
> +Jika pada kedua index ini tidak ditemukan nilai yang kita cari maka kita akan memprediksi posisi nilai ini berada diantara 3 bagian yang terbetuk oleh cursor tadi, yaitu:
"... nilai ini berada **di antara** 3 bagian ..."

2021-12-12 03:30 UTC, ikr4mm commented on algorithms/Searching/Ternary/README.md
> +Bagian-bagian yang tidak memiliki kemungkinan terdapat nilai yang di cari kita keluarkan dari pencarian, kemudian mengulangi langkah-langkah pencarian sampai cursor satu dan dua bertemu di index yang
"... terdapat nilai yang **dicari** kita keluarkan ..."

2021-12-12 03:30 UTC, ikr4mm commented on algorithms/Searching/Ternary/README.md
> +untuk lebih jelas kita susun dalam bentuk alur kerja dibawah ini.
di bawah

2021-12-12 03:30 UTC, ikr4mm commented on basics/8_fungsi_dasar/README.md
> +Fungsi tanpa nama (anonymous function) atau lebih dikenal dengan nama `closure function` diperkenalkan oleh PHP pada versi 5.3 dan terus digunakan sampai versi php saat ini (pada saat dokumen ini dit
Konsisten "ditulis" nya

2021-12-12 06:26 UTC, kondiak commented on basics/8_fungsi_dasar/README.md
> +Fungsi tanpa nama (anonymous function) atau lebih dikenal dengan nama `closure function` diperkenalkan oleh PHP pada versi 5.3 dan terus digunakan sampai versi php saat ini (pada saat dokumen ini dit
Siap om, terima kasih masukannya

2021-12-14 14:29 UTC, kondiak commented
Mohon masukan dari rekan-rekan bellshade

2021-12-14 18:00 UTC, wildanie12 approved these changes
Super mantap om @kondiak .. 
Ada extra job yg dilakukan disini yaitu refactor di beberapa algoritma dan materi yang mana cukup bagus sekali.
Soal Algoritma ternary, dari sisi cara kerja algoritma dan pengambaran bagaimana algoritma bekerja dalam teks saya rasa sudah mantep banget lah. 
menunggu review kembali oleh docs

2021-12-15 11:45 UTC, feri-irawan approved these changes
Woah mantap banget om @kondiak 👍🏻

2021-12-18 16:12 UTC, merged