add: Algoritma Selection Sort
bellshade/PHP pull request #136
Opened 2021-12-21 07:09 UTC by Aerysh

Closes #91 

## Deskripsi (Description)

- [ ] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [ ] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [x] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (I am using):

- `os` = `linux`

## Testing

- [x] Codesniffer PSR-12 `phpcs`
- [x] Codesniffer autofix `phpcbf`
- [x] Unit testing PHPUnit

## Maintainer

2021-12-22 04:08 UTC, ikr4mm requested changes
Untuk bagian dokumentasi, kemungkinan sudah bagus. Tinggal mengganti background dari flowchart dan fix error Codacy.

LGTM 🚀🚀

2021-12-22 04:08 UTC, ikr4mm commented on algorithms/Sorting/SelectionSort/SelectionSort.php
> +    public function selectionSort($arr, $n)
Untuk variable `$n` harap diganti dengan nama variabel yang mungkin lebih dari 3 karakter sesuai [error di sini](https://app.codacy.com/gh/bellshade/PHP/pullRequest?prid=8604335).

2021-12-22 04:08 UTC, ikr4mm commented on algorithms/Sorting/SelectionSort/README.md
> +![selection-sort-flowchart](../../../assets/content/algorithms/Sorting/SelectionSort/selection-sort-flowchart.png)
Kalau bisa, tolong ganti background flowcharnya menjadi warna putih karena kalau pakai Github Dark Mode bakal ga keliatan

2021-12-22 16:33 UTC, kondiak commented
Saat ini terlihat sangat baik 👍🏻

Terima kasih atas kontribusinya

2021-12-22 16:37 UTC, kondiak approved these changes
Saat ini terlihat sangat bagus bagi saya,
Terimakasih atas kontribusinya om 🙏

2021-12-23 10:14 UTC, ikr4mm approved these changes
Ok, dokumentasi aman. 👍

2022-01-08 14:44 UTC, merged