add: penjelasan operator ternary
bellshade/PHP pull request #177
Opened 2022-10-01 07:13 UTC by malvinval

![PenjelasanOperatorTernary](https://user-images.githubusercontent.com/78136971/193397638-51f24152-cd23-4744-b67b-403fbb003025.png)
![PenjelasanOperatorTernary2](https://user-images.githubusercontent.com/78136971/193397655-1b4111d3-ca46-4de8-b899-356f303bccc2.png)

### Linked issue : #176

2022-10-01 11:50 UTC, slowy07 commented on basics/4_conditional_statements/3_operator_ternary.php
> +
coba hapus whitespace disini

2022-10-01 11:51 UTC, slowy07 commented on basics/4_conditional_statements/5_ternary_shorthand.php
> +
coba hilangkan whitespace pada line ini

2022-10-01 11:52 UTC, slowy07 commented on basics/4_conditional_statements/4_ternary_assignment.php
> +
coba hapus whitespace pada line ini

2022-10-01 11:52 UTC, slowy07 commented on basics/4_conditional_statements/5_ternary_shorthand.php
> +
coba hapus whitespace pada line ini

2022-10-01 11:54 UTC, slowy07 requested changes
coba hapus whitespace pada ``line 2 - 4_ternary_assignment.php``
dan juga ``line 14 - 5_ternary_shorthand.php``

log error bisa dilihat disini
[codacy](https://app.codacy.com/gh/bellshade/PHP/pullRequest?prid=10281584)
[git action psr](https://github.com/bellshade/PHP/actions/runs/3163706821/jobs/5152712611)

2022-10-01 14:22 UTC, malvinval commented on basics/4_conditional_statements/4_ternary_assignment.php
> +
baik

2022-10-01 14:23 UTC, malvinval commented on basics/4_conditional_statements/4_ternary_assignment.php
> +
dihapus untuk semua file ?

2022-10-02 00:50 UTC, malvinval commented on basics/4_conditional_statements/5_ternary_shorthand.php
> +
done

2022-10-02 00:50 UTC, malvinval commented on basics/4_conditional_statements/4_ternary_assignment.php
> +
done

2022-10-02 01:54 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @malvinval

2022-10-02 01:56 UTC, merged