add : Menambahkan materi Abstract Class
bellshade/PHP pull request #209
Opened 2023-09-05 10:44 UTC by kvnrynfl

Closes 

## Deskripsi (Description)

- [x] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [x] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [ ] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [x] saya sudah membaca _(I have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [x] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (I am using):

- `os` = `linux`

## Testing

- [ ] Codesniffer PSR-12 `phpcs`
- [ ] Codesniffer autofix `phpcbf`
- [ ] Unit testing PHPUnit

## Maintainer

2023-09-06 01:36 UTC, MuhammadNazhimMaulana approved these changes
LGTM

2023-09-06 04:53 UTC, sensasi-delight requested changes
- cuplik dan jelaskan kode program yang penting pada `README.md` agar pembaca dapat memahami maksud dari program tersebut. baca subbab ini (https://github.com/bellshade/PHP/tree/main/basics/14_oop_dasar#7-setter-dan-getter) untuk dijadikan referensi kerangka menulis.
- ketika menulis, posisikan diri juga sebagai pembaca yang ingin memahami tentang Abstract Class.
- pada #149 dituliskan `Satu lagi bahwa kelas abstrak tidak dapat di instantiasi oleh sebuah objek, ada baiknya jika didemonstrasikan juga. Harapannya adalah keluar error.`. sedangkan belum terdapat pada kode program.
- _file_ program (`*.php`) dapat dipisah-pisah untuk meningkatkan fokus dan penyelarasan antara kode program dan pembahasan.

2023-09-06 04:53 UTC, sensasi-delight commented on basics/15_oop_lanjutan/5_abstract_class.php
> +echo "
kode PHP jangan di-`echo` pada program PHP. ini akan membingungkan pembaca. sebutkan dan jelaskan program pada `README.md` saja

2023-09-06 04:53 UTC, sensasi-delight commented on basics/15_oop_lanjutan/README.md
> +Abstract class (kelas abstrak) adalah salah satu konsep penting dalam pemrograman berorientasi objek (OOP) yang digunakan untuk menciptakan kerangka kerja (template) bagi kelas-kelas turunannya. Abst
- kata-kata berbahasa inggris ditulis dengan huruf miring, misal: _template_. untuk kata "Abstract Class" mendapatkan pengecualian karena objek utama tulisan.
- penggunaan kata sambung `Sebaliknya` kurang tepat, tidak cocok dengan kalimat sebelumnya dan setelahnya.
- penggunaan tanda kurung yang tidak tepat pada kalimat `.... memiliki definisi (nama dan parameter) ....`.
- ganti kata `menciptakan` dengan kata lain. karena dalam konteks menulis kode program tidak ada diciptakan. hanya disusun dan dibangun.

2023-09-06 11:21 UTC, kvnrynfl commented on basics/15_oop_lanjutan/5_abstract_class.php
> +echo "
Sudah saya perbaiki, mohon di review kembali.

2023-09-06 11:21 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +Abstract class (kelas abstrak) adalah salah satu konsep penting dalam pemrograman berorientasi objek (OOP) yang digunakan untuk menciptakan kerangka kerja (template) bagi kelas-kelas turunannya. Abst
Sudah saya perbaiki, mohon di review kembali.

2023-09-06 12:07 UTC, sensasi-delight requested changes
Harap disempurnakan lagi, terima kasih.

2023-09-06 12:07 UTC, sensasi-delight commented on basics/15_oop_lanjutan/README.md
> +```
- tidak ada kalimat yang mengantarkan daftar.
- kode tidak di-_indentation_ yang menyebabkan daftar tersebut dianggap berakhir sehingga tulisan ini secara semantik akan menjadi tiga daftar dengan masing-masing satu _item_, padahal yang dimaksud adalah satu daftar dengan tiga _item_

2023-09-06 12:07 UTC, sensasi-delight commented on basics/15_oop_lanjutan/README.md
> +
```suggestion
Kode program di atas akan menghasilkan _output_ seperti berikut:
```

2023-09-06 12:07 UTC, sensasi-delight commented on basics/15_oop_lanjutan/README.md
> +Program ini akan menghasilkan output seperti di atas ketika dijalankan.
```suggestion
```

2023-09-06 12:15 UTC, sensasi-delight commented on basics/15_oop_lanjutan/README.md
> +### Penggunaan Program
apa yang dimaksud dengan `Penggunaan Program`? subjudul tidak sinkron dengan kontennya,

2023-09-06 17:41 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +Abstract Class adalah salah satu konsep penting dalam pemrograman berorientasi objek (OOP) yang digunakan untuk mengorganisir struktur (_template_) bagi kelas-kelas turunannya. Abstract Class sendiri
Sudah saya perbaiki, mohon di review kembali.

2023-09-06 17:41 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +- **Class `BackendDeveloper`**: Ini adalah kelas turunan lainnya yang juga mengimplementasikan metode abstrak `printPerkenalan()`. Kelas ini memiliki metode khusus `apaPekerjaanBackendDeveloper()` ya
Sudah saya perbaiki, mohon di review kembali.

2023-09-06 17:41 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +```
Sudah saya perbaiki, mohon di review kembali.

2023-09-06 17:47 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +
Sudah saya perbaiki, mohon di review kembali.

2023-09-06 17:47 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +Program ini akan menghasilkan output seperti di atas ketika dijalankan.
Sudah saya perbaiki, mohon di review kembali.

2023-09-06 18:35 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +### Penggunaan Program
Sudah saya ubah menjadi Contoh Program.

2023-09-06 18:36 UTC, kvnrynfl commented on basics/15_oop_lanjutan/README.md
> +Program ini memperlihatkan cara membuat objek dari kelas turunan, yaitu `FrontendDeveloper` dan `BackendDeveloper`, serta memanggil metode-metodenya. Meskipun kelas abstrak `Pengguna` tidak dapat dii
Aku ga ngerti ini maksudnya gimana, tapi aku sudah menambahkan informasi pada *Struktur Program*

> sebagai contoh kita menggunakan nama class `Pengguna`, `FrontendDeveloper`, dan `BackendDeveloper` sebagai bagian dari program ini

Source : https://github.com/bellshade/PHP/pull/209/commits/c55bdb9ab61a31039cf53ada38fb227b9a5f7094

2023-09-07 02:00 UTC, sensasi-delight requested changes

2023-09-07 02:00 UTC, sensasi-delight commented on basics/15_oop_lanjutan/README.md
kalau copy-paste dari robot minimal dimodifikasi dan dibaca ulang supaya kalimat-kalimatnya mengalir, runut dan berkesinambungan satu sama lain, supaya ilmu yang terdapat dalam tulisan ter-_deliver_ secara optimal ke pembaca.

Ketika menulis, posisikan diri sebagai pembaca yang sama sekali belum tau tentang kelas abstrak, jadi harus runut poin-poinnya gak bisa lompat-lompat tiba-tiba ada ini itu.

2023-09-07 09:12 UTC, closed without merging