add: menambahkan materi mengenai PHP Loops
bellshade/PHP pull request #39
Opened 2021-10-03 19:45 UTC by chaubatkunda

Closes 

## Deskripsi (Description)

- [ ] saya menambahkan materi basic baru
- [ ] saya memperbaiki materi basic yang sudah ada
- [ ] saya menambahkan materi utility baru
- [ ] saya memperbaiki materi utility sudah ada
- [ ] saya menambahkan dokumentasi/artikel baru
- [ ] saya memperbaiki dokumentasi/artikel yang sudah ada
- [ ] saya menambahkan algoritma baru
- [ ] saya memperbaiki algoritma yang sudah ada

## Contributor Requirements (Syarat Kontributor)

- [ ] saya sudah membaca _(i have read)_ [CONTRIBUTING](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
- [ ] saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat
- [ ] saya sudah membuat artikel `README.md` tentang materi yang saya buat
- [ ] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Environment

saya menggunakan (im used):

- `os` = `linux / windows / macOS`

## Testing

- [ ] Codesniffer PSR-12 `phpcs`
- [ ] Codesniffer autofix `phpcbf`
- [ ] Unit testing PHPUnit

## Maintainer

2021-10-04 01:14 UTC, wildanie12 requested changes
Halo bang, workflow kami mendeteksi ada kesalahan gaya penulisan yang nggak mengikuti standard PSR-12
coba lakukan perintah ini untuk memperbaiki secara otomatis
```
composer phpcbf
```
lalu lakukan 
```
composer phpcs
```
pastikan tidak ada error. 
Setelah itu, bisa langsung commit dan push ke PR ini lagi.

2021-10-04 02:52 UTC, wildanie12 approved these changes

2021-10-04 03:45 UTC, merged

2021-10-04 03:47 UTC, wildanie12 commented
Terima kasih telah berkontribusi di Bellshade PHP bang terkait Issue #41 
Karena sub materi masih belum sepenuhnya lengkap kami belum bisa menutup Issuenya agar bisa diteruskan lagi progressnya. 👍

2021-10-05 02:18 UTC, nomadkode reviewed
tidak ada typo dan miskonteks. LGTM pada PR ini meskipun issue belom sepenuhnya lengkap. 👍🏼